config/routes.rb
Rails.application.routes.draw do
  devise_for :mecanicos, controllers: { sessions: 'custom_sessions' }
  devise_scope :mecanico do
    authenticated :mecanico do
      root 'main#home', as: :authenticated_root

      get '/admin/register_mecanico', to: 'mecanicos#new', as: 'new_admin_mecanico'
      post '/admin/register_mecanico', to: 'mecanicos#create', as: 'admin_mecanicos'
      get '/mecanicos', to: 'mecanicos#index', as: 'mecanicos'

      resources :mecanicos, only: [:show]
      resources :mecanicos
      resources :mecanicos do
        post 'deactivate', on: :member
      end

      get '/clientes', to: 'clientes#index', as: 'clientes'
      get '/clientes/new', to: 'clientes#new', as: 'new_cliente'
      post '/clientes', to: 'clientes#create', as: 'create_cliente'
      resources :clientes, only: [:show]
      resources :clientes
      resources :clientes do
        member do
          get 'veiculos', to: 'clientes#veiculos'
        end
      end

      get '/equipes', to: 'equipes#index', as: 'equipes'
      get '/equipes/new', to: 'equipes#new', as: 'new_equipe'
      post '/equipes', to: 'equipes#create', as: 'create_equipe'
      resources :equipes 

      get '/veiculos', to: 'veiculos#index', as: 'veiculos'
      get '/veiculos/new', to: 'veiculos#new', as: 'new_veiculo'
      post '/veiculos/new', to: 'veiculos#create', as: 'create_veiculo'
      resources :veiculos

      get '/pecas', to: 'pecas#index', as: 'pecas'
      get '/pecas/new', to: 'pecas#new', as: 'new_peca'
      post '/pecas', to: 'pecas#create', as: 'create_peca'
      delete '/pecas/:id', to: 'pecas#destroy', as: 'delete_peca'
      resources :pecas

      get '/ordens', to: 'ordens#index', as: 'ordens'
      get '/ordens/new', to: 'ordens#new', as: 'new_ordem'
      get '/ordens/:id', to: 'ordens#show', as: 'show_ordem'
      post '/ordens', to: 'ordens#create', as: 'create_ordem'
      patch '/ordens/:id', to: 'ordens#update', as: 'update_ordem'
      delete '/ordens/:id', to: 'ordens#destroy', as: 'delete_ordem'
      resources :ordens

      get '/home', to: 'main#home', as: 'main_home'
      get '/sign_out', to: 'devise/sessions#destroy', as: 'sign_out'
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    @ordem = Ordem.all
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_nav.html.erb
<nav class="nav">
  <div class="nav-top">
    <div class="profile">
      <%= image_tag("profile.svg", class: "logo") %>
      <h1 class="nome"><%= current_mecanico.nome %></h1>
    </div>

    <ul class="nav-links">
      <div class="linha"></div>
      <li class="stagger">
        <%= image_tag("prancheta.svg") %>
        <%= link_to "Ordens de Serviço", ordens_path, class: "button" %>
      </li>
      <div class="linha"></div>
      <li class="stagger">
        <%= image_tag("profile.svg") %>
        <%= link_to "Clientes", clientes_path, class: "button" %>
      </li>
      <div class="linha"></div>
      <li class="stagger">
        <%= image_tag("nut.svg") %>
        <%= link_to "Peças", pecas_path, class: "button" %>
      </li>
      <div class="linha"></div>
      <li class="stagger">
        <%= image_tag("car.svg") %>
        <%= link_to "Veículos", veiculos_path, class: "button" %>
      </li>
      <div class="linha"></div>
      <li class="stagger">
        <%= image_tag("profile.svg") %>
        <%= link_to "Mecânicos", mecanicos_path, class: "button" %>
      </li>
      <div class="linha"></div>
      <li class="stagger">
        <%= image_tag("team.svg") %>
        <%= link_to "Equipes", equipes_path, class: "button" %>
      </li>
      <div class="linha"></div>
      <li class="stagger">
        <%= image_tag("GoBack.svg") %>
        <%= link_to "Logout", sign_out_path, method: :delete%>
      </li>
      <div class="linha"></div>
    </ul>
  </div>
  <% if current_mecanico && current_mecanico.adminCode == 1 %>
    <h1 class="adm">ADMIN</h1>
  <% end %>
</nav>

<script>
  var flag = 1;
  openNav = () => {
    if (flag == 0) {
      document.querySelector(".nav").style.left = "0";
      setTimeout(() => {
        document.querySelectorAll(".stagger").forEach(element => {
          element.style.visibility = "visible";
          element.style.display = "flex";
        });
      }, 200);
      
      flag = 1;
    } else {
      document.querySelector(".nav").style.left = "-100%";
      setTimeout(() => {
        document.querySelectorAll(".stagger").forEach(element => {
          element.style.visibility = "";
          element.style.display = "";
        });
      }, 600);
      flag = 0;
    }
  }
  openNav();
</script>

<%= image_tag ("hamb.svg"), class: "navBtn", onclick: "openNav()" %>
<%= link_to inline_svg_tag('home.svg', size: '14x14'), main_home_path, class: "voltar home" %>

app/views/main/home.html.erb
<%= render 'main/nav' %>
<main>
  <div class="main-content">
    <div class="main-top">
      <h1>Ordens de Serviço</h1>
    </div>
    <%= link_to "+ Criar Ordem de serviço", new_ordem_path, class: "btn-add" %>
    <div class="main-info">
      <% @ordem.each do |ordem| %>
        <%= link_to "/ordens/#{ordem.id}" do %>
          <div class="card-body">
            <div class="status-line"></div>
            <div class="card-info team">
              <%= image_tag("car.svg", class: "logo") %>
              <div class="carro-placa">
                <h1 class="card-nome"><%= ordem.veiculo.placa %></h1>
                <p class="nome-dono"><%= ordem.cliente.nome %></p>
              </div>
              <div class="carro-placa">
                <h1 class="card-nome"><%= ordem.equipe.nomeEquipe %></h1>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</main>