config/routes.rb
Rails.application.routes.draw do
  devise_for :mecanicos, controllers: { sessions: 'custom_sessions' }
  devise_scope :mecanico do
    authenticated :mecanico do
      root 'main#home', as: :authenticated_root

      get '/admin/register_mecanico', to: 'mecanicos#new', as: 'new_admin_mecanico'
      post '/admin/register_mecanico', to: 'mecanicos#create', as: 'admin_mecanicos'
      get '/mecanicos', to: 'mecanicos#index', as: 'mecanicos'

      resources :mecanicos, only: [:show]
      resources :mecanicos
      resources :mecanicos do
        post 'deactivate', on: :member
      end

      get '/clientes', to: 'clientes#index', as: 'clientes'
      get '/clientes/new', to: 'clientes#new', as: 'new_cliente'
      post '/clientes', to: 'clientes#create', as: 'create_cliente'
      resources :clientes, only: [:show]
      resources :clientes
      resources :clientes do
        member do
          get 'veiculos', to: 'clientes#veiculos'
        end
      end

      get '/equipes', to: 'equipes#index', as: 'equipes'
      get '/equipes/new', to: 'equipes#new', as: 'new_equipe'
      post '/equipes', to: 'equipes#create', as: 'create_equipe'
      resources :equipes 

      get '/veiculos', to: 'veiculos#index', as: 'veiculos'
      get '/veiculos/new', to: 'veiculos#new', as: 'new_veiculo'
      post '/veiculos/new', to: 'veiculos#create', as: 'create_veiculo'
      resources :veiculos

      get '/pecas', to: 'pecas#index', as: 'pecas'
      get '/pecas/new', to: 'pecas#new', as: 'new_peca'
      post '/pecas', to: 'pecas#create', as: 'create_peca'
      delete '/pecas/:id', to: 'pecas#destroy', as: 'delete_peca'
      resources :pecas

      get '/ordens', to: 'ordens#index', as: 'ordens'
      get '/ordens/new', to: 'ordens#new', as: 'new_ordem'
      get '/ordens/:id', to: 'ordens#show', as: 'show_ordem'
      post '/ordens', to: 'ordens#create', as: 'create_ordem'
      patch '/ordens/:id', to: 'ordens#update', as: 'update_ordem'
      delete '/ordens/:id', to: 'ordens#destroy', as: 'delete_ordem'
      resources :ordens

      get '/home', to: 'main#home', as: 'main_home'
      get '/sign_out', to: 'devise/sessions#destroy', as: 'sign_out'
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
end

app/models/equipe.rb
class Equipe < ApplicationRecord
  has_and_belongs_to_many :mecanicos
end

app/controllers/equipes_controller.rb
class EquipesController < ApplicationController
    before_action :check_admin, only: [:new, :create, :edit, :destroy, :update]

    def index
        @equipes = Equipe.all
    end
    
    def show
        @equipe = Equipe.find(params[:id])
    end
    
    def new
        @equipe = Equipe.new
    end
    
    def create
        puts equipe_params.inspect
        @equipe = Equipe.new(equipe_params)
        
        if @equipe.save
            redirect_to '/equipes', notice: 'Equipe was successfully created.'
        else
            render 'new'
        end
    end

    def edit
        @equipe = Equipe.find(params[:id])
    end

    def update
        @equipe = Equipe.find(params[:id])
        if @equipe.update(equipe_params)
            redirect_to @equipe
        else
            render :edit
        end
    end

    def destroy
        @equipe = Equipe.find(params[:id])
        @equipe.destroy
        redirect_to equipes_path
    end

    
    def equipe_params
        params.require(:equipe).permit(:nomeEquipe, mecanico_ids: []).tap do |whitelisted|
          whitelisted[:mecanico_ids].reject!(&:empty?)
        end
      end  
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/views/equipes/edit.html.erb
<%= render 'main/nav'%>
<%= link_to inline_svg_tag('GoBack.svg', size: '14x14'), :back, class: "voltar" %>

<main>
    <div class="main-content">
        <div class="main-top add-mec">
            <h1>Editar Equipe</h1>
        </div>
        <div class="main-info bg-w">
           <%= form_for @equipe, url: equipe_path(@equipe), method: :patch do |f| %>
           <div class="form-log">
                <%= f.text_field :nomeEquipe, placeholder: "Nome"%>
                <div class="nomes-mec">
                    <%= f.collection_check_boxes :mecanico_ids, Mecanico.all, :id, :nome do |b| %>
                        <%= b.check_box %>
                        <%= b.label { b.text } %>
                    <% end %>
                </div>
                <%= f.submit "Atualizar", class: "entrarBtn" %>
            </div>
            <% end %>
        </div>
    </div>
</main>

app/views/equipes/index.html.erb
<%= render 'main/nav'%>
<main>
  <div class="main-content">
    <div class="main-top">
      <h1>Equipes</h1>
    </div>
    <%= link_to "+ Criar Equipe", new_equipe_path, class: "btn-add" %>
    <div class="main-info">
      <% @equipes.each do |equipe| %>
        <%= link_to equipe_path(equipe), class: 'details-button' do %>
          <div class="card-body">
            <div class="status-line"></div>
            <div class="card-info team">
              <%= image_tag("team.svg", class: "logo") %>
              <h1 class="card-nome"><%= equipe.nomeEquipe%></h1>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</main>

app/views/equipes/new.html.erb
<%= render 'main/nav'%>
<%= link_to inline_svg_tag('GoBack.svg', size: '14x14'), :back, class: "voltar" %>

<main>
    <div class="main-content">
        <div class="main-top add-mec">
            <h1>Criar Equipe</h1>
        </div>
        <div class="main-info bg-w">
           <%= form_for @equipe do |f| %>
                <%= f.text_field :nomeEquipe, placeholder: "Nome"%>
                    <%= f.label :mecanico_ids, "Mecanicos" %>
                    <%= f.collection_check_boxes :mecanico_ids, Mecanico.all, :id, :nome %>
                <%= f.submit "Criar", class: "entrarBtn" %>
            <% end %>
        </div>
    </div>
</main>

app/views/equipes/show.html.erb
    <%= render 'main/nav'%>
<%= link_to inline_svg_tag('GoBack.svg', size: '14x14'), equipes_path, class: "voltar" %>

<div class="main-perfil">
<div class="perfil">
    <div class="perfil-top">
      <%= image_tag("team.svg") %>
      <div class="top-info">
        <p class="nome"><%= @equipe.nomeEquipe %></p>
      </div>
    </div>
    <% if current_mecanico.adminCode == 1 %>
      <div class="button-container">
        <%= link_to "Editar", edit_equipe_path(@equipe), class: "editar-button" %>
        <%= button_to "Deletar", equipe_path(@equipe), method: :delete, class: "editar-button red" %>
      </div>
    <% end %>
    <main class="perfil-bottom">
      <div class="main-content">
        <div class="main-top">
          <h1>Mecânicos da equipe</h1>
        </div>
        <div class="main-info">
          <% @equipe.mecanicos.each do |mecanico| %>
                <%= link_to mecanico_path(mecanico), class: 'details-button' do %>
                    <div class="card-body">
                        <% if mecanico.adminCode == 1 %>
                            <div class="status-line" style="background-color: blue;"></div>
                        <% elsif mecanico.ativarCode == 1 %>
                            <div class="status-line"></div>
                        <% else %>
                            <div class="status-line" style="background-color: red;"></div>
                        <% end %>
                        <div class="card-info">
                            <%= image_tag("profile.svg", class: "logo") %>
                            <h1 class="card-nome"><%= mecanico.nome%></h1>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
      </div>
    </main>
  </div>
</div>