config/routes.rb
Rails.application.routes.draw do
  devise_for :mecanicos, controllers: { sessions: 'custom_sessions' }
  devise_scope :mecanico do
    authenticated :mecanico do
      root 'main#home', as: :authenticated_root

      get '/admin/register_mecanico', to: 'mecanicos#new', as: 'new_admin_mecanico'
      post '/admin/register_mecanico', to: 'mecanicos#create', as: 'admin_mecanicos'
      get '/mecanicos', to: 'mecanicos#index', as: 'mecanicos'

      resources :mecanicos, only: [:show]
      resources :mecanicos
      resources :mecanicos do
        post 'deactivate', on: :member
      end

      get '/clientes', to: 'clientes#index', as: 'clientes'
      get '/clientes/new', to: 'clientes#new', as: 'new_cliente'
      post '/clientes', to: 'clientes#create', as: 'create_cliente'
      resources :clientes, only: [:show]
      resources :clientes
      resources :clientes do
        member do
          get 'veiculos', to: 'clientes#veiculos'
        end
      end

      get '/equipes', to: 'equipes#index', as: 'equipes'
      get '/equipes/new', to: 'equipes#new', as: 'new_equipe'
      post '/equipes', to: 'equipes#create', as: 'create_equipe'
      resources :equipes 

      get '/veiculos', to: 'veiculos#index', as: 'veiculos'
      get '/veiculos/new', to: 'veiculos#new', as: 'new_veiculo'
      post '/veiculos/new', to: 'veiculos#create', as: 'create_veiculo'
      resources :veiculos

      get '/pecas', to: 'pecas#index', as: 'pecas'
      get '/pecas/new', to: 'pecas#new', as: 'new_peca'
      post '/pecas', to: 'pecas#create', as: 'create_peca'
      delete '/pecas/:id', to: 'pecas#destroy', as: 'delete_peca'
      resources :pecas

      get '/ordens', to: 'ordens#index', as: 'ordens'
      get '/ordens/new', to: 'ordens#new', as: 'new_ordem'
      get '/ordens/:id', to: 'ordens#show', as: 'show_ordem'
      post '/ordens', to: 'ordens#create', as: 'create_ordem'
      patch '/ordens/:id', to: 'ordens#update', as: 'update_ordem'
      delete '/ordens/:id', to: 'ordens#destroy', as: 'delete_ordem'
      resources :ordens

      get '/home', to: 'main#home', as: 'main_home'
      get '/sign_out', to: 'devise/sessions#destroy', as: 'sign_out'
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
end

app/models/peca.rb
class Peca < ApplicationRecord
    has_and_belongs_to_many :ordens, join_table: 'ordems_pecas'
end

app/controllers/pecas_controller.rb
class PecasController < ApplicationController
    before_action :check_admin, only: [:new, :create, :edit, :destroy, :update]
    def index
        @pecas = Peca.all
    end
    
    def show
        @peca = Peca.find(params[:id])
    end
    
    def new
        @peca = Peca.new
    end
    
    def create
        puts peca_params.inspect
        @peca = Peca.new(peca_params)
        
        if @peca.save
            redirect_to '/pecas'
        else
            render 'new'
        end
    end

    def edit
        @peca = Peca.find(params[:id])
    end

    def update
        @peca = Peca.find(params[:id])
        if @peca.update(peca_params)
            redirect_to @peca
        else
            render :edit
        end
    end

    def destroy
        @peca = Peca.find(params[:id])
        @peca.destroy
        redirect_to pecas_path
    end
    
    private
    
    def peca_params
        params.require(:peca).permit(:nome, :preco)
    end
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/views/pecas/edit.html.erb
    <%= render 'main/nav'%>
<%= link_to inline_svg_tag('GoBack.svg', size: '14x14'), :back, class: "voltar" %>

<main>
    <div class="main-content">
        <div class="main-top add-mec">
            <h1>Editar Peça</h1>
        </div>
        <div class="main-info bg-w">
            <%= form_for @peca, url: peca_path(@peca), method: :patch do |f| %>
                <div class="form-log">
                    <%= f.text_field :nome, placeholder: "Nome" %>
                    <%= f.text_field :preco, placeholder: "Preço" %>
                    <%= f.submit "Editar", class: "entrarBtn" %>
                </div>
            <% end %>
        </div>
    </div>
</main>

app/views/pecas/index.html.erb
<%= render 'main/nav'%>
<main>
    <div class="main-content">
        <div class="main-top">
            <h1>Peças</h1>
        </div>
        <%= link_to "+ Adicionar Peça", new_peca_path, class: "btn-add" %>
        <div class="main-info">
            <% @pecas.each do |peca| %>
                <%= link_to peca_path(peca), class: 'details-button' do %>
                    <div class="card-body">
                      <div class="status-line"></div>
                      <div class="card-info">
                        <%= image_tag("nut.svg", class: "logo") %>
                        <h1 class="card-nome"><%= peca.nome%></h1>
                      </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
</main>

app/views/pecas/new.html.erb
<%= render 'main/nav'%>
<%= link_to inline_svg_tag('GoBack.svg', size: '14x14'), :back, class: "voltar" %>

<main>
    <div class="main-content">
        <div class="main-top add-mec">
            <h1>Adicionar Peça</h1>
        </div>
        <div class="main-info bg-w">
            <%= form_for @peca do |f| %>
                <div class="form-log">
                    <%= f.text_field :nome, placeholder: "Nome"%>
                    <%= f.number_field :preco, step: "0.01", placeholder: "Valor" %>

                    <%= f.submit "Adicionar", class: "entrarBtn" %>
                </div>
            <% end %>
        </div>
    </div>
</main>

app/views/pecas/show.html.erb
            <%= render 'main/nav'%>
    <%= link_to inline_svg_tag('GoBack.svg', size: '14x14'), pecas_path, class: "voltar" %>

    <div class="main-perfil">
        <div class="perfil">
            <div class="perfil-top">
                <%= image_tag("nut.svg") %>
                <div class="top-info">
                    <p class="nome"><%= @peca.nome %></p>
                    <p class="telefone"><strong>Preço:</strong> <%= @peca.preco %></p>
                </div>
            </div>
            <div class="button-container">
                <%= link_to "Editar", edit_peca_path(@peca), class: "editar-button" %>
                <%= button_to "Deletar", delete_peca_path(@peca), method: :delete, class: "editar-button red" %>
            </div>
        </div>
    </div>
    
    </div>
</div>