config/routes.rb
Rails.application.routes.draw do
  devise_for :mecanicos, controllers: { sessions: 'custom_sessions' }
  devise_scope :mecanico do
    authenticated :mecanico do
      root 'main#home', as: :authenticated_root

      get '/admin/register_mecanico', to: 'mecanicos#new', as: 'new_admin_mecanico'
      post '/admin/register_mecanico', to: 'mecanicos#create', as: 'admin_mecanicos'
      get '/mecanicos', to: 'mecanicos#index', as: 'mecanicos'

      resources :mecanicos, only: [:show]
      resources :mecanicos
      resources :mecanicos do
        post 'deactivate', on: :member
      end

      get '/clientes', to: 'clientes#index', as: 'clientes'
      get '/clientes/new', to: 'clientes#new', as: 'new_cliente'
      post '/clientes', to: 'clientes#create', as: 'create_cliente'
      resources :clientes, only: [:show]
      resources :clientes
      resources :clientes do
        member do
          get 'veiculos', to: 'clientes#veiculos'
        end
      end

      get '/equipes', to: 'equipes#index', as: 'equipes'
      get '/equipes/new', to: 'equipes#new', as: 'new_equipe'
      post '/equipes', to: 'equipes#create', as: 'create_equipe'
      resources :equipes 

      get '/veiculos', to: 'veiculos#index', as: 'veiculos'
      get '/veiculos/new', to: 'veiculos#new', as: 'new_veiculo'
      post '/veiculos/new', to: 'veiculos#create', as: 'create_veiculo'
      resources :veiculos

      get '/pecas', to: 'pecas#index', as: 'pecas'
      get '/pecas/new', to: 'pecas#new', as: 'new_peca'
      post '/pecas', to: 'pecas#create', as: 'create_peca'
      delete '/pecas/:id', to: 'pecas#destroy', as: 'delete_peca'
      resources :pecas

      get '/ordens', to: 'ordens#index', as: 'ordens'
      get '/ordens/new', to: 'ordens#new', as: 'new_ordem'
      get '/ordens/:id', to: 'ordens#show', as: 'show_ordem'
      post '/ordens', to: 'ordens#create', as: 'create_ordem'
      patch '/ordens/:id', to: 'ordens#update', as: 'update_ordem'
      delete '/ordens/:id', to: 'ordens#destroy', as: 'delete_ordem'
      resources :ordens

      get '/home', to: 'main#home', as: 'main_home'
      get '/sign_out', to: 'devise/sessions#destroy', as: 'sign_out'
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
end

app/models/mecanico.rb
class Mecanico < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :equipes, optional: true
end

app/controllers/mecanicos_controller.rb
class MecanicosController < ApplicationController
    before_action :authenticate_mecanico!
    before_action :check_admin, only: [:new, :create, :deactivate, :edit, :destroy, :update]
  
    def new
        @mecanico = Mecanico.new
    end

    def create
        @mecanico = Mecanico.new(mecanico_params)
        if @mecanico.save
            redirect_to '/', notice: 'Mecanico was successfully created.'
        else
            render :new
        end
    end

    def index
        @mecanico = Mecanico.all
    end

    def show
        @mecanico = Mecanico.find(params[:id])
    end

    def edit
        @mecanico = Mecanico.find(params[:id])
    end

    def update
        @mecanico = Mecanico.find(params[:id])
        if @mecanico.update(mecanico_params)
          redirect_to @mecanico, notice: 'Mecanico was successfully updated.'
        else
          render :edit
        end
      end

    def deactivate
        if current_mecanico.adminCode == 1
          @mecanico = Mecanico.find(params[:id])
          if @mecanico.ativarCode == 0
            @mecanico.update(ativarCode: 1)
            redirect_to @mecanico, notice: 'User was successfully activated.'
          else
            @mecanico.update(ativarCode: 0)
            redirect_to @mecanico, notice: 'User was successfully deactivated.'
          end
        else
          redirect_to @mecanico, alert: 'You are not authorized to perform this action.'
        end
      end

    def destroy
        @mecanico = Mecanico.find(params[:id])
        @mecanico.destroy
        redirect_to mecanicos_path
    end

    def mecanico_params
        params.require(:mecanico).permit(:email, :password, :nome, :telefone, :especialidade, :endereco)
    end
end

app/views/mecanicos/edit.html.erb
    <%= render 'main/nav'%>
<%= link_to inline_svg_tag('GoBack.svg', size: '14x14'), :back, class: "voltar" %>

<main>
    <div class="main-content">
        <div class="main-top add-mec">
            <h1>Editar Mecânico</h1>
        </div>
        <div class="main-info bg-w">
            <%= form_for @mecanico, url: mecanico_path(@mecanico), method: :patch do |f| %>
                <div class="form-log">
                    <%= f.text_field :nome, placeholder: "Nome" %>
                    <%= f.email_field :email, placeholder: "Email" %>
                    <%= f.text_field :especialidade, placeholder: "Especialidade" %>
                    <%= f.text_field :telefone, placeholder: "Telefone" %>
                    <%= f.text_field :endereco, placeholder: "Endereço" %>            
                    <%= f.password_field :password, placeholder: "Senha" %>
                    <%= f.submit "Editar", class: "entrarBtn" %>
                </div>
            <% end %>
        </div>
    </div>
</main>

app/views/mecanicos/index.html.erb
<%= render 'main/nav'%>
<main>
    <div class="main-content">
        <div class="main-top">
            <h1>Mecânicos</h1>
        </div>
        <% if current_mecanico && current_mecanico.adminCode == 1 %>
            <%= link_to "Registrar Mecânico", new_admin_mecanico_path, class: "btn-add" %>
        <% end %>
        <div class="main-info">
            <% @mecanico.each do |mecanico| %>
                <%= link_to mecanico_path(mecanico), class: 'details-button' do %>
                    <div class="card-body">
                        <% if mecanico.adminCode == 1 %>
                            <div class="status-line" style="background-color: blue;"></div>
                        <% elsif mecanico.ativarCode == 1 %>
                            <div class="status-line"></div>
                        <% else %>
                            <div class="status-line" style="background-color: red;"></div>
                        <% end %>
                        <div class="card-info team">
                                <%= image_tag("profile.svg", class: "logo") %>
                                <h1 class="card-nome"><%= mecanico.nome%></h1>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
</main>

app/views/mecanicos/new.html.erb
    <%= render 'main/nav'%>
<%= link_to inline_svg_tag('GoBack.svg', size: '14x14'), :back, class: "voltar" %>

<main>
    <div class="main-content">
        <div class="main-top add-mec">
            <h1>Adicionar Mecânico</h1>
        </div>
        <div class="main-info bg-w">
            <%= form_for @mecanico, url: admin_mecanicos_path do |f| %>
                <div class="form-log">
                    <%= f.text_field :nome, placeholder: "Nome" %>
                    <%= f.email_field :email, placeholder: "Email" %>
                    <%= f.text_field :especialidade, placeholder: "Especialidade" %>
                    <%= f.text_field :telefone, placeholder: "Telefone" %>
                    <%= f.text_field :endereco, placeholder: "Endereço" %>            
                    <%= f.password_field :password, placeholder: "Senha" %>
                    <%= f.submit "Adicionar", class: "entrarBtn" %>
                </div>
            <% end %>
        </div>
    </div>
</main>

app/views/mecanicos/show.html.erb
    <%= render 'main/nav'%>
    <%= link_to inline_svg_tag('GoBack.svg', size: '14x14'), mecanicos_path, class: "voltar" %>

    <div class="main-perfil">
        <div class="perfil">
            <div class="perfil-top">
                <% if @mecanico.adminCode == 1 %>
                    <div class="status-perfil" style="background-color: blue;"></div>
                <% elsif @mecanico.ativarCode == 1 %>
                    <div class="status-perfil"></div>
                <% else %>
                    <div class="status-perfil" style="background-color: red;"></div>
                <% end %>
                <%= image_tag("profile.svg") %>
                <div class="top-info">
                    <p class="nome"><%= @mecanico.nome %></p>
                    <p class="email">Email: <%= @mecanico.email %></p>
                    <p class="endereco">Endereço: <%= @mecanico.endereco%> </p>
                    <p class="telefone">Telefone: <%= @mecanico.telefone %></p>
                </div>
            </div>
            <div class="perfil-bottom">
            <% if current_mecanico.adminCode == 1 && @mecanico.adminCode == 0 %>
            <div class="button-mec">
                <% if @mecanico.ativarCode == 1 %>
                    <%= button_to 'Desativar', deactivate_mecanico_path(@mecanico), method: :post, class: 'editar-button red mec-top' %>
                <% else %>
                    <%= button_to 'Ativar', deactivate_mecanico_path(@mecanico), method: :post, class: 'editar-button green mec-top' %>
                <% end %>
                <div class="button-container">
                    <%= link_to 'Edit', edit_mecanico_path(@mecanico), class: 'editar-button' %>
                    <%= button_to "Deletar", mecanico_path(@mecanico), method: :delete, class: "editar-button red" %>
                </div>
            </div>
            <% end %>
                <main class="perfil-bottom">
                 <div class="main-content">
                   <div class="main-top">
                     <h1>Equipes do Mecânico</h1>
                   </div>
                   <div class="main-info">
                     <% @mecanico.equipes.each do |equipe|  %>
                      <%= link_to equipe_path(equipe), class: 'details-button' do %>
                           <div class="card-body">
                               <div class="status-line"></div>
                               <div class="card-info team">
                                   <%= image_tag("team.svg", class: "logo") %>
                                   <h1 class="card-nome"><%= equipe.nomeEquipe %></h1>
                               </div>
                           </div>
                       <% end %>
                     <% end %>
                   </div>
                 </div>
                </main>
            </div>
      </div>
    </div>